add
Zerrgg/go-first-floor-sprint-five pull request #1
Opened 2023-11-21 16:15 UTC by Zerrgg

2023-11-23 13:48 UTC, just-musha requested changes
Привет! Есть не большие правки по коду. Поправь пожалуйста константу и проверки на 0.

Опционально: вижу, что ответы у некоторых формул не сходятся, но пока тесты ещё в процессе разработки, тут сложно что-то подсказать. Проверь ещё раз все формулы на всякий случай. Возможно позже добавят тесты, будет понятнее что не так, и нужно будет поправить. Будешь проверять, обрати внимание на Calories для Walking и дистанция и ср.скорость в Плавании, тк там не сходятся ответы на тестовых данных, которые в функции main даны. Это не критично сейчас.

В остальном все хорошо, все что нужно реализовано, так держать!

2023-11-23 13:48 UTC, just-musha commented on main.go
> +	return t.distance() / t.Duration.Hours()
А что будет, если Duration = 0 ?

Предлагаю добавить такую проверку, и возвращать возвращать из функции 0 в этом случае

2023-11-23 13:48 UTC, just-musha commented on main.go
> +	Speed        float64       // средняя скорость, с которой двигался пользователь
Название лучше использовать по смыслу - тк это средняя скорость, то лучше так и её назвать MeanSpeed. Мало ли потом будет добавлена ещё какая-то скорость, минимальная, максимальная и т.д.

2023-11-23 13:48 UTC, just-musha commented on main.go
> +	ms := math.Pow(w.meanSpeed()*1000/3600, 2.0)
Лучше вместо 1000/3600 использовать уже заведенную в коде константу - KmHInMsec, с тем же значением) Это будет лучше для читаемости кода, не надо думать что за числа

2023-11-23 13:48 UTC, just-musha commented on main.go
> +	return (CaloriesWeightMultiplier*w.Weight + (ms/w.Height)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours
Проверь ещё разок формулу. В чем измеряется рост и не нужно ли его привести к другим единицам

На тестовых данных в main должно получиться 947.82 (пишу так пока нет тестов)

2023-11-23 13:48 UTC, just-musha commented on main.go
> -	// вставьте ваш код ниже
Здесь тоже проверка на Duration = 0

2023-11-23 14:21 UTC, just-musha reviewed
Важный комментарий добавила. Нужно поправить TrainingInfo для Swimming, чтобы в ней вызывался корректный метод расчета средней скорости.

2023-11-23 14:21 UTC, just-musha commented on main.go
> +	return s.Training.TrainingInfo()
Вот здесь важнsый момент: в running/walking у нас скорость расчитывается по "базовой" формуле, которая есть в Training.
В случае с плаванием, скорость вычисляется в конкретной реализации meanSpeed для Swimming. Здесь тебе нужно завести структуру InfoMessage и там явно вызвать метод s.meanSpeed() для Swimming, и вернуть эту структуру

2023-11-24 07:50 UTC, Zerrgg commented on main.go
> +	return t.distance() / t.Duration.Hours()
Done

2023-11-24 07:50 UTC, Zerrgg commented on main.go
> +	Speed        float64       // средняя скорость, с которой двигался пользователь
Done

2023-11-24 07:52 UTC, Zerrgg commented on main.go
> +	ms := math.Pow(w.meanSpeed()*1000/3600, 2.0)
Done

2023-11-24 08:10 UTC, Zerrgg commented on main.go
> -	// вставьте ваш код ниже
Done

2023-11-24 08:20 UTC, Zerrgg commented on main.go
> +	return s.Training.TrainingInfo()
Done

2023-11-24 08:34 UTC, Zerrgg commented on main.go
> +	return (CaloriesWeightMultiplier*w.Weight + (ms/w.Height)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours
Done

2023-11-24 09:05 UTC, just-musha approved these changes
Спасибо! Все супер. Оставила небольшое предложение, как можно улучшить код, для выполнения задания это не критично.

Готова принять работу.

2023-11-24 09:05 UTC, just-musha commented on main.go
> +	info.Distance = float64(s.LengthPool) * float64(s.CountPool) / MInKm
Вот тут по сути вычисляешь distance. Как насчет использовать существующий метод distance() из базовой структуры? Чтобы избежать дублирования функциональности - когда одно и то же реализовано по разному в двух местах

2023-11-24 12:50 UTC, Zerrgg commented on main.go
> +	info.Distance = float64(s.LengthPool) * float64(s.CountPool) / MInKm
Done

2023-11-24 12:51 UTC, merged